package io.openems.edge.controller.api.eos;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Controller Api Eos Measurement", //
		description = "Liest periodisch die kumulierten Energiezaehlerstaende (PV-Erzeugung, Verbrauch, "
				+ "Netzbezug, Netzeinspeisung) sowie die aktuelle Batterieleistung/-SoC aus '_sum' und sendet "
				+ "sie ueber eine Bridge.Eos-Instanz an ein Akkudoktor-EOS-System. Die Key-Namen muessen exakt "
				+ "mit den in EOS' eigener Konfiguration verwendeten Measurement-Keys uebereinstimmen "
				+ "(abfragbar per 'GET /v1/measurement/keys' auf dem laufenden EOS-Server).")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlApiEosMeasurement0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Bridge-EOS-ID", description = "Component-ID der Bridge.Eos-Instanz.")
	String bridgeEos_id() default "bridgeEos0";

	@AttributeDefinition(name = "Push-Intervall [Cycles]", //
			description = "Alle wie viele Cycles (typischerweise 1s je Cycle) ein neuer Messwert an EOS "
					+ "gesendet wird. EOS optimiert stundenweise, ein sehr kurzes Intervall ist daher meist "
					+ "unnoetig.")
	int pushEveryCycles() default 60;

	@AttributeDefinition(name = "PV-Produktion Key", //
			description = "EOS-Measurement-Key fuer die kumulierte PV-Erzeugung (entspricht einem Eintrag in "
					+ "EOS' pv_production_emr_keys). Quelle: _sum/ProductionActiveEnergy.")
	String pvProductionKey() default "pv_total-production-kwh";

	@AttributeDefinition(name = "Verbrauch Key", //
			description = "EOS-Measurement-Key fuer den kumulierten Verbrauch (entspricht einem Eintrag in "
					+ "EOS' load_emr_keys). Quelle: _sum/ConsumptionActiveEnergy.")
	String consumptionKey() default "hausverbrauch-kwh";

	@AttributeDefinition(name = "Netzbezug Key", //
			description = "EOS-Measurement-Key fuer den kumulierten Netzbezug (entspricht einem Eintrag in "
					+ "EOS' grid_import_emr_keys). Quelle: _sum/GridBuyActiveEnergy.")
	String gridImportKey() default "netzbezug-kwh";

	@AttributeDefinition(name = "Netzeinspeisung Key", //
			description = "EOS-Measurement-Key fuer die kumulierte Netzeinspeisung (entspricht einem Eintrag "
					+ "in EOS' grid_export_emr_keys). Quelle: _sum/GridSellActiveEnergy.")
	String gridExportKey() default "netzeinspeisung-kwh";

	@AttributeDefinition(name = "Batterie SoC Key", //
			description = "EOS-Measurement-Key fuer den Batterie-Ladezustand als Faktor [0.0 ... 1.0] "
					+ "(EOS' BatteriesCommonSettings.measurement_key_soc_factor). Quelle: _sum/EssSoc "
					+ "(0..100 %, wird durch 100 geteilt).")
	String batterySocKey() default "byd_hvm_16.6-soc-factor";

	@AttributeDefinition(name = "Batterie Leistung L1 Key", //
			description = "EOS-Measurement-Key fuer die Batterieleistung Phase L1 [W] - negativ = Laden, "
					+ "positiv = Entladen (OpenEMS-Konvention, empirisch als mit EOS uebereinstimmend "
					+ "verifiziert, siehe readme.adoc). Quelle: _sum/EssActivePowerL1.")
	String batteryPowerL1Key() default "byd_hvm_16.6-power-l1-w";

	@AttributeDefinition(name = "Batterie Leistung L2 Key", //
			description = "Wie 'Batterie Leistung L1 Key', fuer Phase L2. Quelle: _sum/EssActivePowerL2.")
	String batteryPowerL2Key() default "byd_hvm_16.6-power-l2-w";

	@AttributeDefinition(name = "Batterie Leistung L3 Key", //
			description = "Wie 'Batterie Leistung L1 Key', fuer Phase L3. Quelle: _sum/EssActivePowerL3.")
	String batteryPowerL3Key() default "byd_hvm_16.6-power-l3-w";

	@AttributeDefinition(name = "Batterie Leistung symmetrisch Key", //
			description = "EOS-Measurement-Key fuer die symmetrische 3-phasige Batterieleistung [W] "
					+ "(EOS' measurement_key_power_3_phase_sym_w). Quelle: _sum/EssActivePower.")
	String batteryPowerSymKey() default "byd_hvm_16.6-power-3-phase-sym-w";

	@AttributeDefinition(name = "Bridge-Eos target filter", description = "This is auto-generated by 'Bridge-EOS-ID'.")
	String bridgeEos_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Controller Api Eos Measurement [{id}]";
}
